# 2nd-init by Skrilax_CZ

LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES := 2nd-init.c
LOCAL_MODULE := 2nd-init
LOCAL_MODULE_TAGS := optional

LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_STATIC_LIBRARIES := libc

include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_CFLAGS += -DLIBRARY_VERSION
LOCAL_SRC_FILES := 2nd-init.c
LOCAL_STATIC_LIBRARIES := libc
LOCAL_MODULE := lib2nd-init
LOCAL_MODULE_TAGS := eng
include $(BUILD_STATIC_LIBRARY)
